[package]
name = "htmx_actix_ecomm_starter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
futures = "*"
serde = { version = "1.0.188", features = ["derive"] }
tera = "*"